add new file
kugaitomomi/menta pull request #1
Opened 2020-12-16 21:29 UTC by kugaitomomi

コードレビューお願いいたします。

2020-12-16 23:05 UTC, kuma47 commented on main.js
> +for(i = 1; i < 100; i++){
iが変数として宣言されていないためエラーが起きています。
しっかりと変数として宣言しましょう。

2020-12-16 23:05 UTC, kuma47 commented on main.js
> + }
変数iと%と数字の間にインデントを1ずつ作りましょう。
またifと（）の間、（）と｛｝の間にもインデントを1つ空けるとよくなります！
if文を全体的に見るとインデントがズレているようなので揃えていただけたらgoodです^^

2020-12-16 23:05 UTC, kuma47 commented on index.html
> +<html lang="en">
こちら今回は英語のみなのでlang="en"で問題ないのですが、今後日本語を出力する課題になった際はlang="ja"にしましょう。

2020-12-16 23:05 UTC, kuma47 commented on index.html
> +  <script src="main.js"></script>
scriptファイルはbodyタグの最下部に記述しましょう。

2020-12-20 06:49 UTC, myzktkyk requested changes
確認しました。1点だけ指摘がございます。

2020-12-20 06:49 UTC, myzktkyk commented on kadai1-2/main.js
> +var result = prompt("日本の首都はなんですか？");
`var` は昨今ではほとんど使われません。
 `const` `let` を利用するようにしてください。
今回のように再度代入をしない場合は `const` にしましょう。

2020-12-20 07:47 UTC, kugaitomomi commented
修正行いました。
確認お願いいたします。

2020-12-22 00:39 UTC, niganium reviewed
1-3確認しました。問題ありません！引き続き後続の課題をお願いいたします！！

2020-12-23 11:13 UTC, merged