add kadai1_4 file.
kugaitomomi/menta pull request #2
Opened 2020-12-23 11:16 UTC by kugaitomomi

課題①-4をプッシュしました。
ご確認よろしくお願いいたします。

2020-12-23 14:04 UTC, myzktkyk requested changes
何点か指摘がございます。
全体的な指摘としてはコードのインデントがずれている箇所が散見されるので
コミット前にコードのフォーマット（整形）をする習慣をつけましょう。
エディターのショートカットで簡単にできますよ。

2020-12-23 14:04 UTC, myzktkyk commented on main.js
> +}
`forEach` を使う方がすっきり書けますよ。

```suggestion
list.forEach((task, index) => {
  console.log(`${i} : [内容] ${task.task}、[ジャンル] ${task.genre}`);
});
```

2020-12-23 14:04 UTC, myzktkyk commented on main.js
> +  }
- `var` は昨今ではほとんど使われないので `let` または `const` を使いましょう
- 変数名は「何が入っているか」一見してわかる名前である方が好ましいです
- 配列への要素の追加は `push` という便利なものがあります

```suggestion
const task = prompt("タスクを入力してください");
const genre = prompt("ジャンルを入力してください");
list.push({task: task, genre: genre})
```

2020-12-23 21:14 UTC, kugaitomomi commented on main.js
> +}
${i}ですが、
Uncaught ReferenceError: i is not defined
と指摘うけました。
indexで定義されているので、${index}になるのではないんでしょうか？
ご教示お願いいたします。

2020-12-25 01:43 UTC, kouki-iwahara commented on main.js
> +lists.push({ task: task, genre: genre });
オブジェクトはkeyとvalueが一致している場合、以下のように省略記法が使用できます。
`{ task }`

2020-12-25 01:43 UTC, kouki-iwahara commented on main.js
> +}
そうですね、おっしゃる通りです。

2020-12-25 01:44 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

以下にもご返信しております。
https://github.com/kugaitomomi/menta/pull/2#discussion_r548243311

2020-12-25 20:37 UTC, merged